# Generated by Django 3.1.7 on 2021-08-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('path', models.SlugField(max_length=255)),
                ('context', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(blank=True, max_length=55, null=True)),
                ('lng', models.CharField(blank=True, max_length=55, null=True)),
                ('pin', models.FileField(null=True, upload_to=projects.models.makeDynamicPinImagePath)),
                ('pin_width', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_height', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.FileField(null=True, upload_to=projects.models.makeDynamicLogoImagePath)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='accounts.company')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permission', to='accounts.permission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_display_google_map', models.BooleanField(default=True)),
                ('can_display_vista', models.BooleanField(default=True)),
                ('can_display_room_vr', models.BooleanField(default=True)),
                ('can_display_color', models.BooleanField(default=True)),
                ('can_display_blueprints', models.BooleanField(default=True)),
                ('can_display_plan', models.BooleanField(default=True)),
                ('can_display_document', models.BooleanField(default=True)),
                ('can_display_gallery', models.BooleanField(default=True)),
                ('can_display_links', models.BooleanField(default=True)),
                ('can_display_building', models.BooleanField(default=True)),
                ('can_display_loan', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limitation', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.salon'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(through='projects.ProjectRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PinImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=projects.models.makeDynamicPinImagePath)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_image', to='projects.project')),
            ],
        ),
    ]
