# Generated by Django 3.1.7 on 2021-08-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlimitation',
            name='can_display_vr',
            field=models.BooleanField(default=False),
        ),
    ]
