# Generated by Django 3.1.7 on 2021-12-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '__first__'),
        ('projects', '0004_project_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAppRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('title', models.CharField(max_length=40, null=True)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='salons.salon'),
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.AddField(
            model_name='projectapproutes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_routes', to='projects.project'),
        ),
    ]
