# Generated by Django 3.1.7 on 2021-12-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211217_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproutes',
            name='path',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
