# Generated by Django 3.1.7 on 2021-12-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectapproutes_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlimitation',
            name='project',
        ),
        migrations.DeleteModel(
            name='PinImage',
        ),
        migrations.DeleteModel(
            name='ProjectLimitation',
        ),
    ]
