# Generated by Django 3.1.7 on 2022-01-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211217_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo_height',
            field=models.CharField(default='auto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_width',
            field=models.CharField(default='200px', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pin_height',
            field=models.CharField(default='25', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pin_width',
            field=models.CharField(default='25', max_length=255, null=True),
        ),
    ]
