# Generated by Django 3.1.7 on 2022-01-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220106_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproutes',
            name='component',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectapproutes',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectapproutes',
            name='path',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectapproutes',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
