# Generated by Django 3.1.7 on 2022-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220106_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapproutes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
