# Generated by Django 3.1.7 on 2022-01-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectapproutes_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAppRoutes',
        ),
    ]
