# Generated by Django 3.1.7 on 2022-01-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
