# Generated by Django 3.1.7 on 2022-02-01 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20220201_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='permissionitem',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_items', to='projects.permission'),
        ),
    ]
