# Generated by Django 3.1.7 on 2022-02-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20220218_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='token_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='projects.project'),
        ),
    ]
