# Generated by Django 3.1.7 on 2022-03-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20220218_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionitem',
            name='code_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
