# Generated by Django 3.1.7 on 2022-03-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_permissionitem_code_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionitem',
            old_name='project',
            new_name='permission',
        ),
    ]
