# Generated by Django 3.1.7 on 2022-03-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='code_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='PermissionItem',
        ),
    ]
