# Generated by Django 3.1.7 on 2022-03-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20220307_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.project'),
        ),
    ]
