# Generated by Django 3.1.7 on 2022-03-08 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
        ('projects', '0025_auto_20220307_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.route'),
        ),
    ]
