# Generated by Django 3.1.7 on 2022-03-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20220308_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.calendar'),
        ),
    ]
