# Generated by Django 3.1.7 on 2022-03-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_calendarevent_is_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start',
        ),
    ]
