# Generated by Django 3.1.7 on 2022-03-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20220309_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
