# Generated by Django 3.1.7 on 2022-03-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20220309_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='display',
            field=models.CharField(default='background', max_length=30, null=True),
        ),
    ]
