# Generated by Django 3.1.7 on 2022-03-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20220309_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(default='#4834d4', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='display',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
