# Generated by Django 3.1.7 on 2022-03-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20220310_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='holiday_codes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
