# Generated by Django 3.1.7 on 2022-03-10 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_auto_20220310_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='rendering',
            new_name='display',
        ),
    ]
