# Generated by Django 3.1.7 on 2022-03-10 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20220310_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='all_day',
            new_name='allDay',
        ),
    ]
