# Generated by Django 3.1.7 on 2022-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_auto_20220324_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proute',
            name='panel_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
