# Generated by Django 3.1.7 on 2022-03-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20220324_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
