# Generated by Django 3.1.7 on 2022-04-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_project_active'),
        ('projects', '0042_auto_20220418_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='permissions.user'),
        ),
    ]
