# Generated by Django 3.1.7 on 2022-04-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20220418_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
        migrations.AddField(
            model_name='role',
            name='edit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
