# Generated by Django 3.1.7 on 2022-04-18 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_auto_20220418_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='project_roles', through='projects.Role', to=settings.AUTH_USER_MODEL),
        ),
    ]
