# Generated by Django 3.1.7 on 2022-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220307_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
