# Generated by Django 3.1.7 on 2022-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='panel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
