# Generated by Django 3.1.7 on 2022-03-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='panel',
            new_name='panel_name',
        ),
    ]
