import {Form} from "@/types/Form";

// @ts-ignore
export const form: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "time",
          type: "text",
          model: "昼",
          label: "時間帯",
          hint: null,
          required: true,
          rules: [],
          id: "day_time_input",
          disabled: false,
          // @ts-ignore
          options: [{name: "昼", value: "昼"}, {name: "夕", value: "夕"}, {name: "夜", value: "夜"}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "repeat",
          type: "text",
          model: true,
          label: "ループ",
          hint: null,
          required: true,
          rules: [],
          id: "loop_input",
          disabled: false,
          // @ts-ignore
          options: [{name: "する", value: true}, {name: "しない", value: false}, ],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },

        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "is_bg",
          type: "text",
          model: false,
          label: "表示方法",
          hint: null,
          required: true,
          rules: [],
          id: "bg_input",
          disabled: false,
          // @ts-ignore
          options: [{name: "パノラマ表示", value: false}, {name: "背景画像表示", value: true}, ],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputNumber",
          db_column_name: "floor_num",
          type: "text",
          model: null,
          label: "階数",
          hint: "数字だけで入力してください",
          placeholder: "3",
          required: true,
          id: "floor_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "plan_type",
          type: "text",
          model: null,
          label: "タイプ",
          hint: null,
          placeholder: "AB",
          required: false,
          id: "type_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "FileInput",
          db_column_name: "image",
          type: "text",
          model: null,
          label: "画像",
          hint: ".jpeg, .png がサポートされています",
          required: false,
          id: "image_input",
          preview_text: "アップロードのため、クリックや画像ドロップしてください",
          limit: "1MB以下",
          accept: "image/*",
          rules: [],
          rule: null,
          disabled: false,
          props: ["placeholder", "required", "disabled", "accept", "hint", "model", "image_path", "preview_text", "limit", "rule"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
    // { // form row
    //   classes: ["flex"],
    //   elements: [ // columns
    //     { // columns in row
    //       component: null,
    //       name: "SliderInput",
    //       db_column_name: "compass_start",
    //       model: 20,
    //       label: "観点",
    //       hint: "スライダーでスタートポイントの設定できます",
    //       id: "slider_input",
    //       min: 4,
    //       max: 360,
    //       disabled: false,
    //       props: ["placeholder", "required", "disabled", "min", "max"],
    //       classes: ["flex-column", "column-1"],
    //     },
    //   ],
    // },
  ]
]
