import {Form} from "../../../types/Form";

export const form: Form[] = [
  { // form row
    classes: ["flex"],
    elements: [ // columns
      { // columns in row
        component: null,
        name: "Dropdown",
        db_column_name: "name",
        type: "text",
        model: null,
        label: "",
        hint: null,
        required: false,
        rules: [],
        id: "",
        disabled: false,
        options: [],
        optionLabel: "name",
        optionValue: "id",
        placeholder: "選択",
        appendTo: "body",
        props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
        classes: ["flex-column", "column-1", "relative"],
      },
    ],
  },
  { // form row
    classes: ["flex", "justify-space-between"],
    elements: [ // columns
      { // columns in row
        component: null,
        name: "InputText",
        db_column_name: "name",
        type: "text",
        model: null,
        label: "",
        hint: null,
        placeholder: "ー",
        required: false,
        id: "",
        rules: [],
        disabled: false,
        props: ["placeholder", "required", "disabled"],
        classes: ["flex-column", "column-1"],
      },
    ],
  },
  { // form row
    classes: ["flex", "justify-space-between"],
    elements: [ // columns
      { // columns in row
        component: null,
        name: "InputNumber",
        db_column_name: "name",
        type: "text",
        model: 0,
        label: "",
        hint: null,
        placeholder: "ー",
        required: false,
        id: "",
        rules: [],
        disabled: false,
        props: ["placeholder", "required", "disabled"],
        classes: ["flex-column", "column-1"],
      },
    ],
  },
  { // form row
    classes: ["flex"],
    elements: [ // columns
      { // columns in row
        component: null,
        name: "FileInput",
        db_column_name: "value",
        type: "text",
        model: null,
        label: "PIN",
        hint: ".jpeg, .png サポートされています",
        required: false,
        id: "pin_input",
        preview_text: "アップロードのため、クリックや画像ドロップしてください",
        limit: "1MB以下",
        accept: "image/*",
        rules: [],
        rule: null,
        disabled: false,
        props: ["placeholder", "required", "disabled", "accept", "hint", "model", "preview_text"],
        classes: ["flex-column", "column-1"],
      },
    ],
  },
]
