import {Form} from "@/types/Form";
import {isRomaji, isRomajiWithIrregulars, isSpace} from "@/components/form/rules";

export const form: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "active",
          type: "text",
          model: true,
          label: "アクティブ",
          hint: null,
          required: true,
          rules: [],
          id: "active_input",
          disabled: false,
          options: [{name: "オン", value: true}, {name: "オフ", value: false},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "状態選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-1", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "component",
          type: "text",
          model: null,
          label: "コンポーネント名",
          hint: null,
          placeholder: "map",
          required: true,
          id: "component_input",
          rules: [isSpace, isRomaji],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "name",
          type: "text",
          model: null,
          label: "ルート名",
          hint: null,
          placeholder: "map",
          required: true,
          id: "name_input",
          rules: [isSpace, isRomaji],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "panel_name",
          type: "text",
          model: null,
          label: "パネル名",
          hint: null,
          placeholder: "map",
          required: true,
          id: "name_input",
          rules: [isSpace, isRomaji],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "path",
          type: "text",
          model: null,
          label: "URLパス",
          hint: null,
          placeholder: "project-map",
          required: true,
          id: "path_input",
          rules: [isSpace, isRomajiWithIrregulars],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "title",
          type: "text",
          model: null,
          label: "タイトル",
          hint: null,
          placeholder: "地図",
          required: true,
          id: "title_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
  ],
]

