import {Form} from "@/types/Form";
import {isMail, isSpace} from "@/components/form/rules";

export const form: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "is_remove_scheduled",
          type: "text",
          model: false,
          label: "削除スケジュール",
          hint: "使用期間終わると、削除したい場合「はい」を選択",
          required: false,
          rules: [],
          id: "remove_scheduled_input",
          disabled: false,
          options: [{name: "はい", value: true}, {name: "いいえ", value: false},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "CalendarInput",
          db_column_name: "remove_date",
          type: "text",
          model: new Date(),
          label: "使用終了日",
          hint: "削除スケジュールは「はい」の場合時運用される",
          placeholder: "",
          required: false,
          id: "remove_date_input",
          rules: [],
          dateFormat:"yy年mm月dd日",
          appendTo: "self",
          disabled: false,
          props: ["placeholder", "required", "disabled", "dateFormat", "appendTo"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "last_name",
          type: "text",
          model: null,
          label: "姓",
          hint: null,
          placeholder: "田中",
          required: true,
          id: "last_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "first_name",
          type: "text",
          model: null,
          label: "名",
          hint: null,
          placeholder: "太郎",
          required: true,
          id: "first_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "username",
          type: "text",
          model: null,
          label: "ユーザー名",
          hint: "*ログインするために使われます",
          placeholder: "tanaka",
          required: true,
          id: "username_input",
          rules: [isSpace],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "email",
          type: "text",
          model: null,
          label: "メールアドレス",
          hint: null,
          placeholder: "tanaka.tarou@reactool.jp",
          required: true,
          id: "email_input",
          rules: [isMail],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "password",
          type: "text",
          model: null,
          label: "パスワード",
          hint: null,
          placeholder: "",
          required: true,
          id: "password_input",
          rules: [isSpace],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],
]
