import {Form} from "@/types/Form";
import {isImageNone, isImageValid} from "@/components/form/rules";

export const form: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "all",
          type: "text",
          model: true,
          label: "全て表示",
          hint: null,
          required: false,
          rules: [],
          id: "all_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "administrative",
          type: "text",
          model: true,
          label: "住所名",
          hint: null,
          required: false,
          rules: [],
          id: "administrative_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "poi",
          type: "text",
          model: true,
          label: "スポット",
          hint: null,
          required: false,
          rules: [],
          id: "poi_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "road",
          type: "text",
          model: true,
          label: "道路",
          hint: null,
          required: false,
          rules: [],
          id: "road_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "water",
          type: "text",
          model: true,
          label: "水域",
          hint: null,
          required: false,
          rules: [],
          id: "water_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "line",
          type: "text",
          model: true,
          label: "電車ライン",
          hint: null,
          required: false,
          rules: [],
          id: "line_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "station",
          type: "text",
          model: true,
          label: "駅",
          hint: null,
          required: false,
          rules: [],
          id: "station_input",
          disabled: false,
          options: [{name: "表示", value: true}, {name: "未表示", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "FileInput",
          db_column_name: "pin",
          type: "text",
          model: null,
          label: "PIN",
          hint: ".jpeg, .png, .svg サポートされています",
          required: false,
          id: "place_image_input",
          preview_text: "アップロードのため、クリックや画像ドロップしてください",
          limit: "1MB以下",
          accept: "image/*",
          rules: [isImageNone],
          rule: isImageValid,
          disabled: false,
          props: ["placeholder", "required", "disabled", "accept", "hint", "model", "image_path", "preview_text", "limit", "rule"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ]
]
