import {Form} from "@/types/Form";
import useStore from "@/stores/main"
import {isRomajiWithIrregulars, isImageValid, isImageNone, isSpace} from "@/components/form/rules";

export const create: Form[][] = [
  [
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "salon",
          type: "text",
          model: null,
          label: "サロン",
          hint: null,
          required: true,
          rules: [],
          id: "salon_name_input",
          disabled: false,
          options: [],
          optionLabel: "name",
          optionValue: "id",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-1", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "name",
          type: "text",
          model: null,
          label: "プロジェクト名",
          hint: null,
          placeholder: "〇〇プロジェクト",
          required: true,
          id: "project_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },

    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "path",
          type: "text",
          model: null,
          label: "プロジェクトフォルダーパス",
          hint: "*スペースなしで入力してください",
          placeholder: "nani_nani_project",
          required: true,
          id: "project_path_input",
          rules: [isSpace, isRomajiWithIrregulars],
          disabled: !useStore().user?.is_staff,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ]
]

export const update: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "name",
          type: "text",
          model: null,
          label: "プロジェクト名",
          hint: null,
          placeholder: "〇〇プロジェクト",
          required: true,
          id: "project_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },

    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "address",
          type: "text",
          model: null,
          label: "住所",
          hint: null,
          placeholder: "〇〇プロジェクト",
          required: true,
          id: "address_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Textarea",
          db_column_name: "context",
          type: "text",
          model: null,
          label: "コメント",
          hint: null,
          placeholder: "〇〇プロジェクト",
          required: false,
          autoResize: false,
          rows: "10",
          cols: "30",
          id: "context_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled", "autoResize"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],
  [ // tab
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "token_on",
          type: "text",
          model: false,
          label: "トークン権限",
          hint: "*特別リンクでアプリページの表示",
          required: false,
          rules: [],
          id: "salon_name_input",
          disabled: false,
          options: [{name: "トークン権限あり", value: true}, {name: "トークン権限なし", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "権限選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "archive",
          type: "text",
          model: true,
          label: "ステータス",
          hint: null,
          required: false,
          rules: [],
          id: "salon_name_input",
          disabled: false,
          options: [{name: "アクティブ", value: false}, {name: "アーカイブ", value: true}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "salon_view",
          type: "text",
          model: true,
          label: "表示状態",
          hint: "*トップページにサロン全部出すかどうか",
          required: false,
          rules: [],
          id: "salon_name_input",
          disabled: false,
          options: [{name: "サロンの中でみる", value: true}, {name: "一つだけでみる", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "legacy",
          type: "text",
          model: false,
          label: "アプリバージョン",
          hint: "app.reactoolバージョン",
          required: false,
          rules: [],
          id: "legacy_input",
          disabled: false,
          options: [{name: "レガシー v1", value: true}, {name: "reactool v1.5", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
      ],
    },

    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "salon",
          type: "text",
          model: null,
          label: "サロン",
          hint: null,
          required: true,
          rules: [],
          id: "salon_name_input",
          disabled: false,
          options: useStore().salons,
          optionLabel: "name",
          optionValue: "id",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-1", "relative"],
        },
      ],
    },
  ],

  [ // tab 3
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "pin_width",
          type: "text",
          model: null,
          label: "PIN幅",
          hint: "*数字はpxとして運用されます",
          placeholder: "30",
          required: true,
          id: "project_path_input",
          rules: [],
          disabled: !useStore().user?.is_staff,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "pin_height",
          type: "text",
          model: null,
          label: "PIN高さ",
          hint: null,
          placeholder: "auto",
          required: true,
          id: "project_path_input",
          rules: [],
          disabled: !useStore().user?.is_staff,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "FileInput",
          db_column_name: "pin",
          type: "text",
          model: null,
          label: "画像",
          hint: ".jpeg, .png, .svg サポートされています",
          required: false,
          id: "pin_input",
          preview_text: "アップロードのため、クリックや画像ドロップしてください",
          limit: "1MB以下",
          accept: "image/*",
          rules: [isImageNone],
          rule: isImageValid,
          disabled: false,
          props: ["placeholder", "required", "disabled", "accept", "hint", "model", "preview_text", "limit", "rule"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],

  [ // tab 4
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "logo_place",
          type: "text",
          model: null,
          label: "配置",
          hint: null,
          required: false,
          rules: [],
          id: "logo_place_input",
          disabled: false,
          options: [{name: "左上", value: 1}, {name: "左下", value: 2}, {name: "右上", value: 3}, {
            name: "右下",
            value: 4
          }, {name: "中央", value: 5},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "logo_width",
          type: "text",
          model: null,
          label: "ロゴ幅",
          hint: "*数字はpxとして運用されます",
          placeholder: "200",
          required: true,
          id: "project_path_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "logo_height",
          type: "text",
          model: null,
          label: "ロゴ高さ",
          hint: null,
          placeholder: "auto",
          required: true,
          id: "project_path_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "FileInput",
          db_column_name: "logo",
          type: "text",
          model: null,
          label: "画像",
          hint: ".jpeg, .png, .svg サポートされています",
          required: false,
          id: "logo_input",
          preview_text: "アップロードのため、クリックや画像ドロップしてください",
          limit: "1MB以下",
          accept: "image/*",
          rules: [isImageNone],
          rule: isImageValid,
          disabled: false,
          props: ["placeholder", "required", "disabled", "accept", "hint", "model", "preview_text", "limit", "rule"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],

  [ // tab 4
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "logo_place",
          type: "text",
          model: null,
          label: "配置",
          hint: null,
          required: false,
          rules: [],
          id: "logo_place_input",
          disabled: false,
          options: [{name: "左上", value: 1}, {name: "左下", value: 2}, {name: "右上", value: 3}, {
            name: "右下",
            value: 4
          }, {name: "中央", value: 5},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "logo_place",
          type: "text",
          model: null,
          label: "",
          hint: null,
          required: false,
          rules: [],
          id: "logo_place_input",
          disabled: false,
          options: [{name: "左上", value: 1}, {name: "左下", value: 2}, {name: "右上", value: 3}, {
            name: "右下",
            value: 4
          }, {name: "中央", value: 5},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "サロン選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
  ],
]

