import {Form} from "@/types/Form";

export const form: Form[][] = [
  [
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "title",
          type: "text",
          model: null,
          label: "イベント名",
          hint: null,
          placeholder: "新規イベント",
          required: false,
          id: "title_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "is_holiday",
          type: "text",
          model: true,
          label: "休日設定",
          hint: null,
          required: false,
          rules: [],
          id: "is_holiday_input",
          disabled: false,
          options: [{name: "休日", value: true}, {name: "平日", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "color",
          type: "text",
          model: true,
          label: "イベントカラー",
          hint: null,
          required: false,
          rules: [],
          id: "color_input",
          disabled: false,
          options: [{name: "紫", value: "#27ae60"}, {name: "緑", value: "#27ae60"}, {name: "青い", value: "#3498db"}, {name: "赤い", value: "#e74c3c"}, {name: "ダーク", value: "#34495e",}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "CalendarInput",
          db_column_name: "start",
          type: "text",
          model: new Date(),
          label: "イベント開始日",
          hint: null,
          placeholder: "null",
          required: true,
          id: "start_date_input",
          rules: [],
          dateFormat: "yy年mm月dd日",
          showTime: true,
          hourFormat: "24",
          disabled: false,
          appendTo: "self",
          props: ["placeholder", "required", "disabled", "dateFormat", "appendTo", "showTime", "hourFormat"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "CalendarInput",
          db_column_name: "end",
          type: "text",
          model: new Date(),
          label: "イベント終了日",
          hint: null,
          placeholder: "null",
          required: true,
          id: "end_date_input",
          rules: [],
          dateFormat: "yy年mm月dd日",
          showTime: true,
          hourFormat: "24",
          appendTo: "self",
          disabled: false,
          props: ["placeholder", "required", "disabled", "dateFormat", "appendTo", "showTime", "hourFormat"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },

  ]
]
