import {Form} from "@/types/Form";

export const form: Form[][] = [
  [
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "sub",
          type: "text",
          model: false,
          label: "種類",
          hint: "非住戸はテキストのみ表示されます",
          required: false,
          rules: [],
          id: "sub_input",
          disabled: false,
          options: [{name: "非住戸", value: true}, {name: "部屋", value: false},],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "sub_content",
          type: "text",
          model: null,
          label: "テキスト",
          hint: "非住戸の場合、表示されるテキスト",
          placeholder: "エントランス",
          required: false,
          id: "sub_content_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "status",
          type: "text",
          model: "商談中",
          label: "ステータス",
          hint: null,
          required: false,
          rules: [],
          id: "status_input",
          disabled: false,
          options: [{name: "販売中", value: "販売中"}, {name: "商談中", value: "商談中"}, {
            name: "次期分譲",
            value: "次期分譲"
          }, {name: "完売済", value: "完売済"}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "number",
          type: "text",
          model: null,
          label: "号室",
          hint: null,
          placeholder: "201",
          required: false,
          id: "number_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "type",
          type: "text",
          model: null,
          label: "タイプ",
          hint: null,
          placeholder: "AB",
          required: false,
          id: "type_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "menu",
          type: "text",
          model: "販売中",
          label: "メニュー",
          hint: "空の場合、先にメニューを作成してください",
          required: false,
          rules: [],
          id: "menu_input",
          disabled: false,
          // @ts-ignore
          options: [],
          optionLabel: "name",
          optionValue: "id",
          placeholder: "選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "plan",
          type: "text",
          model: null,
          label: "プラン",
          hint: null,
          placeholder: "3LDK",
          required: false,
          id: "plan_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "m2",
          type: "text",
          model: null,
          label: "専有面積",
          hint: null,
          placeholder: "80.40",
          required: false,
          id: "m2_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "price",
          type: "text",
          model: "",
          label: "金額",
          hint: "数字飲みで、単位を万円として入力してください",
          placeholder: "ー",
          required: false,
          id: "price_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-3-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputNumber",
          db_column_name: "management_fee",
          type: "text",
          model: null,
          label: "管理費",
          hint: null,
          placeholder: "ー",
          required: false,
          id: "management_fee_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
        { // columns in row
          component: null,
          name: "InputNumber",
          db_column_name: "fixing_fee",
          type: "text",
          model: null,
          label: "修繕積立金",
          hint: null,
          placeholder: "ー",
          required: false,
          id: "fixing_fee_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "FileInput",
          db_column_name: "image",
          type: "text",
          model: null,
          label: "間取り画像",
          hint: ".jpeg, .png がサポートされています",
          required: false,
          id: "image_input",
          preview_text: "アップロードのため、クリックや画像ドロップしてください",
          limit: "1MB以下",
          accept: "image/*",
          rules: [],
          rule: null,
          disabled: false,
          props: ["placeholder", "required", "disabled", "accept", "hint", "model", "preview_text"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],
]
