import {Form} from "@/types/Form";
import {isMail} from "@/components/form/rules";

export const update: Form[][] = [
  [ // tab
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "company",
          type: "text",
          model: null,
          label: "会社",
          hint: null,
          required: true,
          rules: [],
          id: "company_name_input",
          disabled: true,
          options: [],
          optionLabel: "name",
          optionValue: "id",
          placeholder: "会社選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-1", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "last_name",
          type: "text",
          model: null,
          label: "姓",
          hint: null,
          placeholder: "田中",
          required: true,
          id: "last_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "first_name",
          type: "text",
          model: null,
          label: "名",
          hint: null,
          placeholder: "太郎",
          required: true,
          id: "first_name_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "username",
          type: "text",
          model: null,
          label: "ユーザー名",
          hint: "*ログインするために使われます",
          placeholder: "tanaka",
          required: true,
          id: "username_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
    { // form row
      classes: ["flex"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "email",
          type: "text",
          model: null,
          label: "メールアドレス",
          hint: null,
          placeholder: "tanaka.tarou@reactool.jp",
          required: true,
          id: "email_input",
          rules: [isMail],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-1"],
        },
      ],
    },
  ],
]


