import {Form} from "@/types/Form";

export const form: Form[][] = [
  [
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "InputText",
          db_column_name: "name",
          type: "text",
          model: null,
          label: "トークン名",
          hint: null,
          placeholder: "AAAお客様",
          required: true,
          id: "token_input",
          rules: [],
          disabled: false,
          props: ["placeholder", "required", "disabled"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "Dropdown",
          db_column_name: "permanent",
          type: "text",
          model: false,
          label: "恒久的",
          hint: "「はい」にすると、期間リミットなしになります",
          required: false,
          rules: [],
          id: "master_token_input",
          disabled: false,
          options: [{name: "はい", value: true}, {name: "いいえ", value: false}],
          optionLabel: "name",
          optionValue: "value",
          placeholder: "権限選択",
          appendTo: "body",
          props: ["placeholder", "required", "disabled", "options", "optionLabel", "optionValue", "appendTo"],
          classes: ["flex-column", "column-2-space", "relative"],
        },
      ],
    },
    { // form row
      classes: ["flex", "justify-space-between"],
      elements: [ // columns
        { // columns in row
          component: null,
          name: "CalendarInput",
          db_column_name: "start_date",
          type: "text",
          model: new Date(),
          label: "見る期間終開始日",
          hint: null,
          placeholder: "null",
          required: true,
          id: "start_date_input",
          rules: [],
          dateFormat:"yy年mm月dd日",
          disabled: false,
          appendTo: "self",
          props: ["placeholder", "required", "disabled", "dateFormat", "appendTo"],
          classes: ["flex-column", "column-2-space"],
        },
        { // columns in row
          component: null,
          name: "CalendarInput",
          db_column_name: "end_date",
          type: "text",
          model: new Date(),
          label: "見る期間終了日",
          hint: null,
          placeholder: "null",
          required: true,
          id: "end_date_input",
          rules: [],
          dateFormat:"yy年mm月dd日",
          appendTo: "self",
          disabled: false,
          props: ["placeholder", "required", "disabled", "dateFormat", "appendTo"],
          classes: ["flex-column", "column-2-space"],
        },
      ],
    },
  ]
]
