# Generated by Django 3.1.7 on 2021-12-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company_manager',
            field=models.BooleanField(default=False),
        ),
    ]
