# Generated by Django 3.1.7 on 2021-12-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('accounts', '0002_customuser_is_company_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.company'),
        ),
    ]
