# Generated by Django 3.1.7 on 2022-02-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211217_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_remove_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remove_date',
            field=models.DateField(null=True),
        ),
    ]
