# Generated by Django 3.1.7 on 2022-03-07 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220307_1312'),
        ('accounts', '0007_newsletter_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='news_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsletter'),
        ),
    ]
