# Generated by Django 3.1.7 on 2022-04-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
