# Generated by Django 3.1.7 on 2021-12-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to='companies.company'),
        ),
    ]
