# Generated by Django 3.1.7 on 2022-01-07 01:05

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import salons.models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_auto_20211217_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_places', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='MapSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clear_all_poi', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_settings', to='salons.salon')),
            ],
        ),
        migrations.CreateModel(
            name='MapPlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=salons.models.makeDynamicMapPlaceImagePath)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=salons.models.makeDynamicMapPlaceImagePath)),
                ('map_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_place_images', to='salons.mapplace')),
            ],
        ),
    ]
