# Generated by Django 3.1.7 on 2022-01-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_mapplace_mapplaceimage_mapsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapplace',
            old_name='project',
            new_name='salon',
        ),
    ]
