# Generated by Django 3.1.7 on 2022-01-07 01:34

from django.db import migrations, models
import salons.models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_auto_20220107_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplace',
            name='active_pin',
            field=models.FileField(null=True, upload_to=salons.models.makeDynamicMapPlaceImagePath),
        ),
        migrations.AddField(
            model_name='mapplace',
            name='default_pin',
            field=models.FileField(null=True, upload_to=salons.models.makeDynamicMapPlaceImagePath),
        ),
    ]
