# Generated by Django 3.1.7 on 2022-01-07 01:46

from django.db import migrations, models
import salons.models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_auto_20220107_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsetting',
            old_name='project',
            new_name='salon',
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='active_pin',
            field=models.FileField(null=True, upload_to=salons.models.makeDynamicMapPlaceImagePath),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='default_pin',
            field=models.FileField(null=True, upload_to=salons.models.makeDynamicMapPlaceImagePath),
        ),
    ]
