# Generated by Django 3.1.7 on 2022-01-07 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_auto_20220107_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapplace',
            old_name='active_pin',
            new_name='pin',
        ),
        migrations.RenameField(
            model_name='mapsetting',
            old_name='active_pin',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='mapplace',
            name='default_pin',
        ),
        migrations.RemoveField(
            model_name='mapsetting',
            name='default_pin',
        ),
    ]
