# Generated by Django 3.1.7 on 2022-01-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0008_mapplace_show_directions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapsetting',
            old_name='clear_all_poi',
            new_name='all',
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='administrative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='line',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='poi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='road',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='station',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='water',
            field=models.BooleanField(default=True),
        ),
    ]
