# Generated by Django 3.1.7 on 2022-01-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0010_auto_20220112_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapplace',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='pin_height',
            field=models.CharField(default='25', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapsetting',
            name='pin_width',
            field=models.CharField(default='25', max_length=255, null=True),
        ),
    ]
