# Generated by Django 3.1.7 on 2022-02-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0012_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='token_on',
            field=models.BooleanField(default=False),
        ),
    ]
