# Generated by Django 3.1.7 on 2021-08-30 00:36

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('sumaipad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomVr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_vr', to='projects.project')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['order_id']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='compass_left_position',
        ),
        migrations.RemoveField(
            model_name='room',
            name='compass_start_degree',
        ),
        migrations.RemoveField(
            model_name='room',
            name='compass_top_position',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vr_compass_diff',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vr_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vr_start_degree',
        ),
        migrations.AddField(
            model_name='room',
            name='madori_thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicRoomMadoriImagePath),
        ),
        migrations.AddField(
            model_name='room',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='madori_image',
            field=models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicRoomMadoriImagePath),
        ),
        migrations.CreateModel(
            name='RoomVrFloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(null=True)),
                ('vr_image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicRoomVrImagePath)),
                ('madori_image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicRoomVrImagePath)),
                ('vr_compass_diff', models.CharField(max_length=4, null=True)),
                ('vr_start_degree', models.CharField(max_length=4, null=True)),
                ('compass_start_degree', models.CharField(max_length=4, null=True)),
                ('compass_top_position', models.CharField(max_length=4, null=True)),
                ('compass_left_position', models.CharField(max_length=4, null=True)),
                ('room_vr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='sumaipad.roomvr')),
            ],
            options={
                'ordering': ['floor'],
            },
        ),
    ]
