# Generated by Django 3.1.7 on 2021-08-31 01:45

from django.db import migrations, models
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0002_auto_20210830_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentfolder',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicLinkImagePath),
        ),
        migrations.AddField(
            model_name='roomvrfloor',
            name='base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomvrfloor',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='LinkImage',
        ),
    ]
