# Generated by Django 3.1.7 on 2021-09-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectlimitation_can_display_vr'),
        ('sumaipad', '0003_auto_20210831_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('menu', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_menus', to='projects.project')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
