# Generated by Django 3.1.7 on 2021-11-16 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211116_0126'),
        ('sumaipad', '0004_planmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='panorama_type',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MapSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_settings', to='projects.project')),
            ],
        ),
    ]
