# Generated by Django 3.1.7 on 2022-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0006_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
