# Generated by Django 3.1.7 on 2022-01-13 08:56

from django.db import migrations, models
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0007_route_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to=sumaipad.models.makeDynamicGalleryImagePath),
        ),
    ]
