# Generated by Django 3.1.7 on 2022-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0008_auto_20220113_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
