# Generated by Django 3.1.7 on 2022-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0009_link_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
