# Generated by Django 3.1.7 on 2022-01-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0010_gallery_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['order_id']},
        ),
    ]
