# Generated by Django 3.1.7 on 2022-01-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0011_auto_20220114_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='document',
            name='document_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sumaipad.documentfolder'),
        ),
    ]
