# Generated by Django 3.1.7 on 2022-01-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0012_auto_20220115_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='document',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
