# Generated by Django 3.1.7 on 2022-01-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0013_auto_20220115_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
