# Generated by Django 3.1.7 on 2022-01-18 01:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_route'),
        ('sumaipad', '0014_auto_20220116_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('show_directions', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(max_length=50, null=True)),
                ('lng', models.CharField(max_length=50, null=True)),
                ('pin', models.FileField(null=True, upload_to=sumaipad.models.makeDynamicMapCategoryImagePath)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_places', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MapPlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicCoordImagePath)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicCoordImagePath)),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_place_images', to='sumaipad.mapplace')),
            ],
        ),
        migrations.RemoveField(
            model_name='coordimage',
            name='coord',
        ),
        migrations.RenameField(
            model_name='mapcategory',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='mapcategory',
            name='pin',
            field=models.FileField(null=True, upload_to=sumaipad.models.makeDynamicMapCategoryImagePath),
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
        migrations.DeleteModel(
            name='CoordImage',
        ),
    ]
