# Generated by Django 3.1.7 on 2022-01-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0016_auto_20220118_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapplace',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='mapplace',
            name='map_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_places', to='sumaipad.mapcategory'),
        ),
    ]
