# Generated by Django 3.1.7 on 2022-01-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_route'),
        ('sumaipad', '0017_auto_20220118_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_container', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='PlanField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('field', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_field', to='projects.project')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='PlanContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_context', to='sumaipad.plancontainer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_context', to='projects.project')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
