# Generated by Django 3.1.7 on 2022-01-19 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0018_plancontainer_plancontext_planfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_contents', to='sumaipad.plan')),
            ],
        ),
        migrations.RenameField(
            model_name='planfield',
            old_name='field',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='plancontext',
            name='plan_container',
        ),
        migrations.RemoveField(
            model_name='plancontext',
            name='project',
        ),
        migrations.RemoveField(
            model_name='planfield',
            name='project',
        ),
        migrations.AddField(
            model_name='plancontext',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='planfield',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_fields', to='sumaipad.plan'),
        ),
        migrations.DeleteModel(
            name='PlanContainer',
        ),
        migrations.AddField(
            model_name='plancontext',
            name='plan_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_contexts', to='sumaipad.plancontent'),
        ),
    ]
