# Generated by Django 3.1.7 on 2022-01-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0019_auto_20220119_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfield',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
