# Generated by Django 3.1.7 on 2022-01-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_route'),
        ('sumaipad', '0020_planfield_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancontent',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planfield',
            name='plan',
        ),
        migrations.AddField(
            model_name='plancontent',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_contents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='planfield',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_fields', to='projects.project'),
        ),
    ]
