# Generated by Django 3.1.7 on 2022-01-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0021_auto_20220119_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plancontext',
            old_name='name',
            new_name='value',
        ),
    ]
