# Generated by Django 3.1.7 on 2022-01-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0022_auto_20220119_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancontent',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='plancontext',
            name='plan_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_contexts', to='sumaipad.planfield'),
        ),
    ]
