# Generated by Django 3.1.7 on 2022-01-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0023_auto_20220119_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_field_options', to='sumaipad.planfield')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
