# Generated by Django 3.1.7 on 2022-01-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0025_auto_20220121_1408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanFieldOptions',
            new_name='PlanFieldOption',
        ),
    ]
