# Generated by Django 3.1.7 on 2022-01-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0026_auto_20220121_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfield',
            name='class_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
