# Generated by Django 3.1.7 on 2022-01-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_route'),
        ('sumaipad', '0027_planfield_class_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanImage',
            new_name='GeneralPlan',
        ),
    ]
