# Generated by Django 3.1.7 on 2022-01-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_delete_route'),
        ('sumaipad', '0028_auto_20220125_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_plans', to='projects.project'),
        ),
    ]
