# Generated by Django 3.1.7 on 2022-01-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0029_auto_20220125_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalplan',
            old_name='plan',
            new_name='kind',
        ),
    ]
