# Generated by Django 3.1.7 on 2022-01-25 09:45

from django.db import migrations, models
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0030_auto_20220125_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalplan',
            name='image',
            field=models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicDirectProjectPath),
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicDirectProjectPath),
        ),
    ]
