# Generated by Django 3.1.7 on 2022-01-27 02:50

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0031_auto_20220125_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFloorRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('compass', models.CharField(max_length=40, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(max_length=40, null=True)),
                ('menu', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('m2', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('management_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('fixing_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('sub', models.BooleanField(default=False)),
                ('sub_content', models.CharField(blank=True, max_length=50, null=True)),
                ('madori_image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicRoomMadoriImagePath)),
                ('madori_thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicRoomMadoriImagePath)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.RenameModel(
            old_name='Floor',
            new_name='BuildingFloor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='buildingfloorroom',
            name='building_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='sumaipad.buildingfloor'),
        ),
    ]
