# Generated by Django 3.1.7 on 2022-01-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0034_auto_20220128_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
