# Generated by Django 3.1.7 on 2022-02-01 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0035_vistasimulatorcontent_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistasimulatorcontent',
            options={'ordering': ['-floor']},
        ),
        migrations.RenameField(
            model_name='vistasimulator',
            old_name='start_position',
            new_name='panorama_start_position',
        ),
    ]
