# Generated by Django 3.1.7 on 2022-02-01 03:53

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220201_1253'),
        ('sumaipad', '0036_auto_20220201_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingVr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_vr', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingVrDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('building_vr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_vr_directions', to='sumaipad.buildingvr')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingVrDirectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicBuildingVrDirectionImagePath)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicBuildingVrDirectionImagePath)),
                ('building_vr_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_vr_direction_images', to='sumaipad.buildingvrdirection')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
