# Generated by Django 3.1.7 on 2022-02-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220201_1253'),
        ('sumaipad', '0037_buildingvr_buildingvrdirection_buildingvrdirectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingvr',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='building_vr', to='projects.project'),
        ),
    ]
