# Generated by Django 3.1.7 on 2022-02-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0038_auto_20220201_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingvrdirection',
            name='building_vr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_vr_directions', to='sumaipad.buildingvr'),
        ),
    ]
