# Generated by Django 3.1.7 on 2022-02-03 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220201_1253'),
        ('sumaipad', '0040_buildingvrdirection_order_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomSimulator',
            new_name='RoomColorSimulator',
        ),
        migrations.RenameModel(
            old_name='RoomSimulatorBaseImage',
            new_name='RoomColorSimulatorBaseImage',
        ),
        migrations.RenameModel(
            old_name='RoomSimulatorColorImage',
            new_name='RoomColorSimulatorColorImage',
        ),
        migrations.RenameModel(
            old_name='RoomSimulatorContent',
            new_name='RoomColorSimulatorContent',
        ),
        migrations.RenameModel(
            old_name='RoomSimulatorContentTitle',
            new_name='RoomColorSimulatorContentTitle',
        ),
        migrations.RenameModel(
            old_name='RoomSimulatorImage',
            new_name='RoomColorSimulatorImage',
        ),
        migrations.AlterModelOptions(
            name='buildingvrdirection',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='roomcolorsimulatorbaseimage',
            old_name='room_simulator',
            new_name='room_color_simulator',
        ),
        migrations.RenameField(
            model_name='roomcolorsimulatorcolorimage',
            old_name='room_simulator_content',
            new_name='room_color_simulator_content',
        ),
        migrations.RenameField(
            model_name='roomcolorsimulatorcontent',
            old_name='room_simulator_content_title',
            new_name='room_color_simulator_content_title',
        ),
        migrations.RenameField(
            model_name='roomcolorsimulatorcontenttitle',
            old_name='room_simulator',
            new_name='room_color_simulator',
        ),
        migrations.RenameField(
            model_name='roomcolorsimulatorimage',
            old_name='room_simulator_content',
            new_name='room_color_simulator_content',
        ),
    ]
