# Generated by Django 3.1.7 on 2022-02-03 04:57

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220201_1253'),
        ('sumaipad', '0041_auto_20220203_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSimulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to=sumaipad.models.makeDynamicBaseSimImagePath)),
                ('thumbnail', django_resized.forms.ResizedImageField(crop=None, default=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to=sumaipad.models.makeDynamicBaseSimImagePath)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_simulator_rooms', to='projects.project')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='ColorSimulatorRoomPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('room_color_simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_parts', to='sumaipad.colorsimulator')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='ColorSimulatorRoomPartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('option', models.BooleanField(default=False, null=True)),
                ('model_room', models.BooleanField(default=False, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('part_image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicColorSimImagePath)),
                ('part_thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to=sumaipad.models.makeDynamicColorSimImagePath)),
                ('color_image', models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicColorSimImagePath)),
                ('color_thumbnail', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to=sumaipad.models.makeDynamicColorSimImagePath)),
                ('color_simulator_room_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_part_items', to='sumaipad.colorsimulatorroompart')),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
        migrations.RemoveField(
            model_name='roomcolorsimulatorbaseimage',
            name='room_color_simulator',
        ),
        migrations.RemoveField(
            model_name='roomcolorsimulatorcolorimage',
            name='room_color_simulator_content',
        ),
        migrations.RemoveField(
            model_name='roomcolorsimulatorcontent',
            name='room_color_simulator_content_title',
        ),
        migrations.RemoveField(
            model_name='roomcolorsimulatorcontenttitle',
            name='room_color_simulator',
        ),
        migrations.RemoveField(
            model_name='roomcolorsimulatorimage',
            name='room_color_simulator_content',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulator',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulatorBaseImage',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulatorColorImage',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulatorContent',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulatorContentTitle',
        ),
        migrations.DeleteModel(
            name='RoomColorSimulatorImage',
        ),
    ]
