# Generated by Django 3.1.7 on 2022-02-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20220201_1253'),
        ('sumaipad', '0042_auto_20220203_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorSimulator',
            new_name='ColorSimulatorRoom',
        ),
        migrations.RenameField(
            model_name='colorsimulatorroompart',
            old_name='room_color_simulator',
            new_name='color_simulator_room',
        ),
    ]
