# Generated by Django 3.1.7 on 2022-02-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0043_auto_20220203_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorsimulatorroom',
            name='color',
        ),
    ]
