# Generated by Django 3.1.7 on 2022-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0044_remove_colorsimulatorroom_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistasimulator',
            name='repeat',
        ),
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='compass_start_degree',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='panorama_start_position',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='pin_left_px',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='pin_top_px',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
