# Generated by Django 3.1.7 on 2022-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0045_auto_20220211_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vistasimulatorcontent',
            options={},
        ),
        migrations.RenameField(
            model_name='vistasimulator',
            old_name='pin_left_px',
            new_name='compass_left',
        ),
        migrations.RenameField(
            model_name='vistasimulator',
            old_name='compass_start_degree',
            new_name='compass_start',
        ),
        migrations.RenameField(
            model_name='vistasimulator',
            old_name='pin_top_px',
            new_name='compass_top',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='pin_left_px',
            new_name='compass_left',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='pin_top_px',
            new_name='compass_top',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='panorama_start_position',
            new_name='day_time',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='floor',
            new_name='floor_num',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='bg',
            new_name='is_bg',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='time',
            new_name='plan_type',
        ),
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='loop',
            new_name='repeat',
        ),
        migrations.RemoveField(
            model_name='vistasimulator',
            name='panorama_start_position',
        ),
        migrations.RemoveField(
            model_name='vistasimulatorcontent',
            name='compass_start_degree',
        ),
        migrations.RemoveField(
            model_name='vistasimulatorcontent',
            name='type',
        ),
        migrations.AddField(
            model_name='vistasimulatorcontent',
            name='compass_start',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
