# Generated by Django 3.1.7 on 2022-02-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0049_auto_20220212_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vistasimulatorcontent',
            old_name='day_time',
            new_name='plan_type',
        ),
    ]
