# Generated by Django 3.1.7 on 2022-02-14 08:54

from django.db import migrations, models
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0050_auto_20220212_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomvr',
            options={'ordering': ['plan_type']},
        ),
        migrations.AlterModelOptions(
            name='roomvrfloor',
            options={'ordering': ['floor_num']},
        ),
        migrations.RenameField(
            model_name='roomvr',
            old_name='type',
            new_name='plan_type',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='compass_left_position',
            new_name='compass_diff',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='compass_start_degree',
            new_name='compass_left',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='compass_top_position',
            new_name='compass_start',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='vr_compass_diff',
            new_name='compass_top',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='floor',
            new_name='floor_num',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='place',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='vr_start_degree',
            new_name='vr_start',
        ),
        migrations.RemoveField(
            model_name='roomvrfloor',
            name='base',
        ),
        migrations.RemoveField(
            model_name='roomvrfloor',
            name='madori_image',
        ),
        migrations.RemoveField(
            model_name='roomvrfloor',
            name='vr_image',
        ),
        migrations.AddField(
            model_name='roomvr',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicRoomVrImagePath),
        ),
        migrations.AddField(
            model_name='roomvrfloor',
            name='image',
            field=models.ImageField(null=True, upload_to=sumaipad.models.makeDynamicRoomVrVirtualImagePath),
        ),
    ]
