# Generated by Django 3.1.7 on 2022-02-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0051_auto_20220214_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomvrfloor',
            name='base',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roomvrfloor',
            name='left',
            field=models.CharField(default='400', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='roomvrfloor',
            name='top',
            field=models.CharField(default='400', max_length=4, null=True),
        ),
    ]
