# Generated by Django 3.1.7 on 2022-02-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0052_auto_20220215_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvrfloor',
            name='compass_diff',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomvrfloor',
            name='compass_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomvrfloor',
            name='compass_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomvrfloor',
            name='compass_top',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roomvrfloor',
            name='vr_start',
            field=models.IntegerField(null=True),
        ),
    ]
