# Generated by Django 3.1.7 on 2022-02-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0053_auto_20220215_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='left',
            new_name='button_left',
        ),
        migrations.RenameField(
            model_name='roomvrfloor',
            old_name='top',
            new_name='button_top',
        ),
    ]
