# Generated by Django 3.1.7 on 2022-02-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0054_auto_20220215_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomvrfloor',
            name='button_left',
        ),
        migrations.RemoveField(
            model_name='roomvrfloor',
            name='button_top',
        ),
        migrations.CreateModel(
            name='RoomVrNextRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_left', models.IntegerField(null=True)),
                ('button_top', models.IntegerField(null=True)),
                ('room_vr_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_rooms', to='sumaipad.roomvrfloor')),
            ],
        ),
    ]
