# Generated by Django 3.1.7 on 2022-02-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0055_auto_20220215_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomvrnextroom',
            old_name='button_left',
            new_name='button_x',
        ),
        migrations.RenameField(
            model_name='roomvrnextroom',
            old_name='button_top',
            new_name='button_y',
        ),
    ]
