# Generated by Django 3.1.7 on 2022-02-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0056_auto_20220216_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomvrnextroom',
            name='next_room',
            field=models.IntegerField(null=True),
        ),
    ]
