# Generated by Django 3.1.7 on 2022-02-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0057_roomvrnextroom_next_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomvrnextroom',
            name='button_x',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomvrnextroom',
            name='button_y',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
