# Generated by Django 3.1.7 on 2022-03-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0058_auto_20220218_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistasimulatorcontent',
            name='plan_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
