# Generated by Django 3.1.7 on 2022-03-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0059_auto_20220304_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantypeimage',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='route',
            name='project',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanTypeImage',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
