# Generated by Django 3.1.7 on 2022-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0061_auto_20220309_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorsimulatorroompart',
            name='column_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
