# Generated by Django 3.1.7 on 2022-04-12 01:50

from django.db import migrations, models
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0063_mapcategory_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalplan',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='generalplan',
            name='image',
            field=models.FileField(null=True, upload_to=sumaipad.models.makeDynamicDirectProjectPath),
        ),
    ]
