# Generated by Django 3.1.7 on 2022-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0067_auto_20220425_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomvrvendor',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='generalplan',
            name='html_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
