# Generated by Django 3.1.7 on 2022-05-13 07:33

from django.db import migrations
import django_resized.forms
import sumaipad.models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0068_auto_20220509_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistasimulatorcontent',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[400, 400], upload_to=sumaipad.models.makeDynamicVistaThumbnailImagePath),
        ),
    ]
