# Generated by Django 3.1.7 on 2022-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0070_colorsimulatorroom_option_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsimulatorroom',
            name='option_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
