# Generated by Django 3.1.7 on 2022-05-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20220516_1442'),
        ('sumaipad', '0072_generalplansettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralPlanSettings',
            new_name='GeneralPlanSetting',
        ),
    ]
