# Generated by Django 3.1.7 on 2022-05-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20220516_1442'),
        ('sumaipad', '0077_auto_20220516_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=10, max_length=255, null=True)),
                ('interest_rate', models.CharField(default=10, max_length=255, null=True)),
                ('interest_rate_max', models.CharField(default=10, max_length=255, null=True)),
                ('deposit', models.CharField(default=10, max_length=255, null=True)),
                ('deposit_max', models.CharField(default=10, max_length=255, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_settings', to='projects.project')),
            ],
        ),
    ]
