# Generated by Django 3.1.7 on 2022-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0078_loansetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansetting',
            name='deposit_step',
            field=models.CharField(default=10, max_length=255, null=True),
        ),
    ]
