# Generated by Django 3.1.7 on 2023-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumaipad', '0079_loansetting_deposit_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapplace',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
