# Generated by Django 3.1.7 on 2022-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('sub_title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='tutorials/video')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='tutorials/video')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorials/images')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
