# Generated by Django 3.1.7 on 2022-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20220404_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialimage',
            name='active',
        ),
        migrations.RemoveField(
            model_name='tutorialimage',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tutorialimage',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tutorialimage',
            name='video_thumbnail',
        ),
        migrations.AddField(
            model_name='tutorialimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/images'),
        ),
    ]
