# Generated by Django 3.1.7 on 2022-04-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20220404_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialimage',
            name='tutorials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_images', to='tutorials.tutorial'),
        ),
    ]
